language: go

go:
- 1.3
- 1.4
- 1.5
- 1.6
- 1.7
- 1.8
- tip

before_install:
- go get -u github.com/axw/gocov/gocov
- go get -u github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover

matrix:
  allow_failures:
  - go: tip

script:
- make build
- make travis
- make cover
- goveralls -service=travis-ci -v -coverprofile=profile.out
